swarmize-dot-com/config/routes.rb
Swarmize::Application.routes.draw do
  root to: "home#show"

  resources :swarms do
    resources :permissions
    resources :api_keys
    resources :graphs do
      member do
        get 'delete'
      end
    end
    resource :csv, :controller => 'csv' do
      #collection do
        #get 'public'
      #end
    end
    member do
      get 'fields'
      get 'preview'
      get 'embed'
      get 'delete'
      get 'latest'
      get 'entrycount'
      get 'code'
      post 'update_fields'
      post 'open'
      post 'close'
      post 'clone'
    end

    collection do
      get 'mine'
      get 'draft'
      get 'live'
      get 'closed'
    end
  end

  resources :users do
    member do
      get 'delete'
      get 'draft'
      get 'live'
      get 'closed'
    end
  end

  resource :search, :controller => "search" do
    member do
      get 'results'
    end
  end

  resources :case_studies
  resources :docs, :controller => 'documentation'

  resource :home, :controller => "home"

  resource :admin, :controller => "admin" do
    collection do
      post 'dummy_up'
      post 'delete_dummy'
      post 'create_dummy_users'
      post 'create_dummy_swarms'
      post 'regenerate_tokens'
    end
  end

  resource :oembed, :controller => "oembed"

  resource :session do
    collection do
      get 'logout'
    end
  end

  if Rails.env.development?
    resources :swarm_imports, :controller => 'swarm_import'
  end

  get '/utils/name_to_code', to: 'utils#name_to_code'

  get '/auth/google_oauth2', :as => 'login'
  get '/auth/google_oauth2/callback', to: 'sessions#callback'

  get 'swarms/:swarm_id/graphs/count/:count_field', to: 'graphs#aggregate_count'
  get 'swarms/:swarm_id/graphs/count/:count_field/:unique_field', to: 'graphs#cardinal_count'
  get 'swarms/:swarm_id/graphs/count_over_time/:count_field/:interval', to: 'graphs#count_over_time'
end

swarmize-dot-com/app/models/graph.rb
class Graph < ActiveRecord::Base
  belongs_to :swarm

  serialize :options
  GRAPH_TYPES = {pie: "Pie",
                 timeseries: "Time Series"}
                 
  def data_url(field, opts={})
    case graph_type
    when 'pie'
      count_url(field,opts)
    when 'timeseries'
      time_series_url(field,opts)
    end
  end

  private

  def count_url(graph_field, opts={})
    if opts[:filter_field]
      "/swarms/#{swarm.token}/graphs/count/#{graph_field}/#{opts[:filter_field]}"
    else
      "/swarms/#{swarm.token}/graphs/count/#{graph_field}"
    end
  end

  def time_series_url(graph_field, opts={})
    opens_at = swarm.opens_at || Time.now
    closes_at = swarm.closes_at || Time.now
    interval = 'hour'
    case (closes_at - opens_at)
    when (1.hour..1.day)
      interval = 'minute'
    when (0..1.hour)
      interval = 'minute'
    end

    "/swarms/#{swarm.token}/graphs/count_over_time/#{graph_field}/#{interval}"
  end
end

swarmize-dot-com/app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  before_filter :scope_to_swarm
  before_filter :check_for_user, :only => %w{index new create edit update delete destroy}
  before_filter :check_user_has_permissions_on_swarm, only: %w{index new create edit update delete destroy}
  before_filter :scope_to_graph, only: %w{edit update delete destroy}

  def index
    @graphs = @swarm.graphs
  end

  def new
    @graph = @swarm.graphs.new
    setup_graphable_fields
  end

  def create
    graph = @swarm.graphs.new(graph_params)
    options = {}
    if !params[:filter_field].blank?
      options[:filter_field] = params[:filter_field]
    end
    graph.options = options
    graph.save
    redirect_to swarm_graphs_path(@swarm)
  end

  def edit
    setup_graphable_fields
  end

  def update
    @graph.update(graph_params)
    options = {}
    if !params[:filter_field].blank?
      options[:filter_field] = params[:filter_field]
    end
    @graph.options = options
    @graph.save
    redirect_to swarm_graphs_path(@swarm)
  end

  def delete
  end

  def destroy
    @graph.destroy
    flash[:success] = "Graph destroyed."
    redirect_to swarm_graphs_path(@swarm)
  end

  def aggregate_count
    results = {}
    @swarm.search.aggregate_count(params[:count_field]).each do |hash|
      results[hash.keys.first] = hash.values.first
    end
    
    render json: results
  end

  def cardinal_count
    results = {}
    @swarm.search.cardinal_count(params[:count_field], params[:unique_field]).each do |hash|
      results[hash.keys.first] = hash.values.first
    end

    render json: results
  end

  def count_over_time
    results = @swarm.search.count_over_time(params[:count_field], params[:interval]).map do |k| 
      field_name = k.keys.first
      data = k[field_name].map do |row|
        t = row.keys.first
        value = row[t]
        {x: t/1000, y: value} # elasticsearch stores in miliseconds
      end
      {name: field_name,
       data: data}
    end

    render json: results
  end

  private

  def scope_to_swarm
    @swarm = Swarm.find_by(token: params[:swarm_id])
    if @swarm && @swarm.draft?
      check_for_user
    end
  end

  def scope_to_graph
    @graph = @swarm.graphs.find(params[:id])
  end

  def check_user_has_permissions_on_swarm
    unless AccessPermission.can_alter?(@swarm, @current_user)
      flash[:error] = "You don't have permission to do that."
      redirect_to root_path
    end
  end

  def graph_params
    params.require(:graph).permit(:title, :graph_type, :field, :filter_field, :viz_type)
  end

  def setup_graphable_fields
    graphable_fields = @swarm.swarm_fields.where(field_type: SwarmField.graphable)
    if graphable_fields.any?
      @graphable_fields = graphable_fields.map do |f|
        [f.field_name, f.field_code]
      end
     @filter_fields = @swarm.swarm_fields.map do |f|
        [f.field_name, f.field_code]
      end
      @graph_types = Graph::GRAPH_TYPES.invert
    end
  end

end

swarmize-dot-com/app/views/graphs/_pie.html.haml
:javascript
  function updateGraphData#{count+1}() {
    window.graphData#{count+1}.fetch();

    setTimeout(function() {
      updateGraphData#{count+1}();
    }, 5000);
  }

  $(document).ready(function() {
    window.graphData#{count+1} = new GraphData({url: '#{graph.data_url(graph.field, {filter_field: graph.options[:filter_field]})}',
                                                graphType: 'pie',
                                                title: '#{escape_apostrophe(graph.title)}',
                                                index: #{count+1}});


    window.graph#{count+1} = new SwarmizePieGraph({model: window.graphData#{count+1}});

    updateGraphData#{count+1}();
  });

swarmize-dot-com/app/views/graphs/_timeseries.html.haml
:javascript
  function updateGraphData#{count+1}() {
    window.graphData#{count+1}.fetch();


    setTimeout(function() {
      updateGraphData#{count+1}();
    }, 5000);
  }

  $(document).ready(function() {
    window.graphData#{count+1} = new GraphData({
                                    url: '#{graph.data_url(graph.field)}',
                                    graphType: 'timeseries',
                                    title: '#{escape_apostrophe(graph.title)}',
                                    index: #{count+1}});

    window.graph#{count+1} = new SwarmizeTimeSeriesGraph({model: window.graphData#{count+1}});

    updateGraphData#{count+1}();
  });

swarmize-dot-com/app/views/graphs/delete.html.haml
- content_for :pagetitle do
  Delete Graph '#{@graph.title}' : Graphs for #{@swarm.name} : 

.page-header.swarmize-header
  %h1 Delete Graph '#{@graph.title}'?

%p Are you sure you want to delete this graph?

%p
  = button_to "Delete", swarm_graph_path(@swarm,@graph), :method => :delete, :class => "btn btn-default"
  or
  = link_to "Return to all graphs for this swarm.", swarm_graphs_path(@swarm)

swarmize-dot-com/app/views/graphs/edit.html.haml
- content_for :pagetitle do
  Edit '#{@graph.title}' : Graphs for #{@swarm.name} : 

.page-header.swarmize-header
  %h1 Edit graph '#{@graph.title}' for #{@swarm.name}

- if @graphable_fields && @graphable_fields.any?
  = form_for [@swarm, @graph], :html => {:class => "form-horizontal"} do |f|
    .form-group
      %label.col-sm-3.control-label Graph title
      .col-sm-6
        = f.text_field :title, :class => 'form-control'
        %span.help-block This is the name of your graph

    .form-group
      %label.col-sm-3.control-label Graph type
      .col-sm-6
        = f.select :graph_type, @graph_types, {}, {:class => 'form-control'}

    .form-group
      %label.col-sm-3.control-label Field to graph
      .col-sm-6
        = f.select :field, @graphable_fields, {}, {:class => 'form-control'}

    .form-group.pie-only
      %label.col-sm-3.control-label Field to aggregate by (optional)
      .col-sm-6
        = select_tag :filter_field, options_for_select(@filter_fields, @graph.options[:filter_field]), :include_blank => true, :class => 'form-control'

    .form-group
      .col-sm-offset-3
        %p= f.submit "Update graph", :class => "btn btn-default"
        %p= link_to "Back to graphs for '#{@swarm.name}'", swarm_graphs_path(@swarm)

- else
  %p There are no graphable fields in this swarm.

:javascript
  function updateGraphFields() {
    var graphType = $("#graph_graph_type").val();
    if(graphType == 'pie') {
      $(".pie-only").show();
    } else {
      $(".pie-only").hide();
    }
  }

  $(document).ready(function() {
    updateGraphFields();
    $("#graph_graph_type").on('change', function() {
      updateGraphFields();
    });
  });

swarmize-dot-com/app/views/graphs/index.html.haml
- content_for :pagetitle do
  Manage Graphs : #{@swarm.name} : 

.page-header.swarmize-header
  %h1 Manage Graphs for #{@swarm.name}

- if @swarm.graphs.any?
  %table.table
    %thead
      %tr
        %th Title
        %th Type
        %th Field being graphed
        %th Options
    %tbody
      - @swarm.graphs.each do |g|
        %tr
          %td= g.title
          %td= g.graph_type
          %td= g.field
          %td= g.options.inspect
          %td
            = link_to "Edit", edit_swarm_graph_path(@swarm,g)
            |
            = link_to "Delete", delete_swarm_graph_path(@swarm,g)


%p= link_to "Create new graph", new_swarm_graph_path(@swarm), :class => "btn btn-default"
%p= link_to "Back to swarm", @swarm

swarmize-dot-com/app/views/graphs/new.html.haml
- content_for :pagetitle do
  New graph : Graphs for #{@swarm.name} : 

.page-header.swarmize-header
  %h1 Create new graph for #{@swarm.name}

- if @graphable_fields && @graphable_fields.any?
  = form_for [@swarm, @graph], :html => {:class => "form-horizontal"} do |f|
    .form-group
      %label.col-sm-3.control-label Graph title
      .col-sm-6
        = f.text_field :title, :class => 'form-control'
        %span.help-block This is the name of your graph

    .form-group
      %label.col-sm-3.control-label Graph type
      .col-sm-6
        = f.select :graph_type, @graph_types, {}, {:class => 'form-control'}

    .form-group
      %label.col-sm-3.control-label Field to graph
      .col-sm-6
        = f.select :field, @graphable_fields, {}, {:class => 'form-control'}

    .form-group.pie-only
      %label.col-sm-3.control-label Field to aggregate by (optional)
      .col-sm-6
        = select_tag :filter_field, options_for_select(@filter_fields), :include_blank => true, :class => 'form-control'

    .form-group
      .col-sm-offset-3
        %p= f.submit "Create graph", :class => "btn btn-default"
        %p= link_to "Back to graphs for '#{@swarm.name}'", swarm_graphs_path(@swarm)

- else
  %p There are no graphable fields in this swarm.

:javascript
  function updateGraphFields() {
    var graphType = $("#graph_graph_type").val();
    if(graphType == 'pie') {
      $(".pie-only").show();
    } else {
      $(".pie-only").hide();
    }
  }

  $(document).ready(function() {
    updateGraphFields();
    $("#graph_graph_type").on('change', function() {
      updateGraphFields();
    });
  });