swarmize-dot-com/config/routes.rb
Swarmize::Application.routes.draw do
  root to: "home#show"

  resources :swarms do
    resources :permissions
    resources :api_keys
    resources :graphs do
      member do
        get 'delete'
      end
    end
    resource :csv, :controller => 'csv' do
      #collection do
        #get 'public'
      #end
    end
    member do
      get 'fields'
      get 'preview'
      get 'embed'
      get 'delete'
      get 'latest'
      get 'entrycount'
      get 'code'
      post 'update_fields'
      post 'open'
      post 'close'
      post 'clone'
    end

    collection do
      get 'mine'
      get 'draft'
      get 'live'
      get 'closed'
    end
  end

  resources :users do
    member do
      get 'delete'
      get 'draft'
      get 'live'
      get 'closed'
    end
  end

  resource :search, :controller => "search" do
    member do
      get 'results'
    end
  end

  resources :case_studies
  resources :docs, :controller => 'documentation'

  resource :home, :controller => "home"

  resource :admin, :controller => "admin" do
    collection do
      post 'dummy_up'
      post 'delete_dummy'
      post 'create_dummy_users'
      post 'create_dummy_swarms'
      post 'regenerate_tokens'
    end
  end

  resource :oembed, :controller => "oembed"

  resource :session do
    collection do
      get 'logout'
    end
  end

  if Rails.env.development?
    resources :swarm_imports, :controller => 'swarm_import'
  end

  get '/utils/name_to_code', to: 'utils#name_to_code'

  get '/auth/google_oauth2', :as => 'login'
  get '/auth/google_oauth2/callback', to: 'sessions#callback'

  get 'swarms/:swarm_id/graphs/count/:count_field', to: 'graphs#aggregate_count'
  get 'swarms/:swarm_id/graphs/count/:count_field/:unique_field', to: 'graphs#cardinal_count'
  get 'swarms/:swarm_id/graphs/count_over_time/:count_field/:interval', to: 'graphs#count_over_time'
end

swarmize-dot-com/app/views/layouts/_flashes.html.haml
- flash.each do |type, message|
  .alert.alert-dismissable.fade.in{:class => bootstrap_class_for(type)}
    %button{:type => 'button', :class => 'close', "data-dismiss" => "alert", "aria-hidden" => true} &times;
    = message

swarmize-dot-com/app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default.navbar-inverse{role: 'navigation', class: ('is_admin' if (@current_user && @current_user.is_admin?) ) }
  .container
    <!-- Brand and toggle get grouped for better mobile display -->
    .navbar-header
      %button.navbar-toggle{:type => 'button', "data-toggle" => 'collapse', 'data-target' => '#navbar-collapse'}
        %span.sr-only Toggle navigation
        %span.icon-bar 
        %span.icon-bar 
        %span.icon-bar 
      = link_to "Swarmize", root_path, class: 'navbar-brand'

    <!-- Collect the nav links, forms, and other content for toggling -->
    #navbar-collapse.navbar-collapse.collapse
      %ul.nav.navbar-nav
        -if @current_user
          %li.dropdown
            %a.dropdown-toggle{:href => "#", "data-toggle" => 'dropdown'}
              Swarms
              %span.caret
            %ul.dropdown-menu{role: 'menu'}
              %li= link_to "Explore all Swarms", swarms_path
              - if @current_user
                %li= link_to "My Swarms", mine_swarms_path
                %li= link_to "Create Swarm", new_swarm_path
                - if Rails.env.development?
                  %li= link_to "Import Swarm from JSON", new_swarm_import_path
        %li= link_to "Case Studies", case_studies_path
        - if @current_user
          %li= link_to "Help", docs_path
      - if @current_user
        %form.navbar-form.navbar-nav{role: 'search', action: results_search_path}
          .form-group
            %input.form-control{placeholder: 'Search', name: 'query'}
          %button.btn.btn-default{type: 'Submit'} Search

      %ul.nav.navbar-nav.navbar-right.navbar-user{:style => ("background-image: url(#{@current_user.image_url})" if @current_user)}
        - if @current_user
          %li
            = link_to @current_user.name, "/users/#{@current_user.id}", :class => "navbar-link"
          %li
            = link_to "Log out", logout_session_path
          -#%li.user-icon
            -#= image_tag @current_user.image_url, :class => 'user-icon'
        - else
          %li= link_to "Log in", login_path

swarmize-dot-com/app/views/layouts/application.html.haml
!!! 5
%html{html_attrs}
  %head
    = csrf_meta_tag
    %meta{:'http-equiv' => "Content-Type", :content => "text/html; charset=utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    = favicon_link_tag
    %title 
      =yield :pagetitle
      Swarmize
      
    = yield :oembed_discovery
    - if Rails.env.production?
      = stylesheet_link_tag "//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"
    - else
      = stylesheet_link_tag "bootstrap.min"
      = stylesheet_link_tag "bootstrap-theme.min"
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
  %body
    = render "layouts/nav"

    .container
      = render "layouts/flashes"
      = yield

swarmize-dot-com/app/views/layouts/embed.html.haml
!!! 5
%html{html_attrs}
  %head
    %meta{:'http-equiv' => "Content-Type", :content => "text/html; charset=utf-8"}
    %meta{:name => "lang", :content => "en"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    %title Swarmize
    = stylesheet_link_tag "bootstrap.min"
    = stylesheet_link_tag "bootstrap-theme.min"
    = stylesheet_link_tag "application"
    = javascript_include_tag "embed"
  %body
    .container
      = yield