swarmize-dot-com/config/routes.rb
Swarmize::Application.routes.draw do
  root to: "home#show"

  resources :swarms do
    resources :permissions
    resources :api_keys
    resources :graphs do
      member do
        get 'delete'
      end
    end
    resource :csv, :controller => 'csv' do
      #collection do
        #get 'public'
      #end
    end
    member do
      get 'fields'
      get 'preview'
      get 'embed'
      get 'delete'
      get 'latest'
      get 'entrycount'
      get 'code'
      post 'update_fields'
      post 'open'
      post 'close'
      post 'clone'
    end

    collection do
      get 'mine'
      get 'draft'
      get 'live'
      get 'closed'
    end
  end

  resources :users do
    member do
      get 'delete'
      get 'draft'
      get 'live'
      get 'closed'
    end
  end

  resource :search, :controller => "search" do
    member do
      get 'results'
    end
  end

  resources :case_studies
  resources :docs, :controller => 'documentation'

  resource :home, :controller => "home"

  resource :admin, :controller => "admin" do
    collection do
      post 'dummy_up'
      post 'delete_dummy'
      post 'create_dummy_users'
      post 'create_dummy_swarms'
      post 'regenerate_tokens'
    end
  end

  resource :oembed, :controller => "oembed"

  resource :session do
    collection do
      get 'logout'
    end
  end

  if Rails.env.development?
    resources :swarm_imports, :controller => 'swarm_import'
  end

  get '/utils/name_to_code', to: 'utils#name_to_code'

  get '/auth/google_oauth2', :as => 'login'
  get '/auth/google_oauth2/callback', to: 'sessions#callback'

  get 'swarms/:swarm_id/graphs/count/:count_field', to: 'graphs#aggregate_count'
  get 'swarms/:swarm_id/graphs/count/:count_field/:unique_field', to: 'graphs#cardinal_count'
  get 'swarms/:swarm_id/graphs/count_over_time/:count_field/:interval', to: 'graphs#count_over_time'
end

swarmize-dot-com/app/views/admin/show.html.haml
- content_for :pagetitle do
  Admin : 

.page-header.swarmize-header
  %h1 Admin tools

%ul.nav.nav-tabs
  %li.active= link_to "Fake Data", "#fake", "data-toggle" => 'tab'
  %li= link_to "Deleted swarms", "#deleted", "data-toggle" => 'tab'
  %li= link_to "Tokens ", "#tokens", "data-toggle" => 'tab'

.tab-content
  #fake.tab-pane.active
    %h2 Fake data

    %p= button_to "Clear out fake data, make fake swarms/users", dummy_up_admin_path, :class => "btn btn-default"
    %p= button_to "Clear out fake data", delete_dummy_admin_path, :class => "btn btn-default"
    %p= button_to "Create dummy users", create_dummy_users_admin_path, :class => "btn btn-default"
    %p= button_to "Create dummy swarms", create_dummy_swarms_admin_path, :class => "btn btn-default"

  #deleted.tab-pane
    %h2 Deleted swarms.
    = render :partial => "swarms/swarm_table", :locals => {:swarms => @deleted_swarms}

  #tokens.tab-pane
    %h2 Tokens
    %p= button_to "Regenerate tokens", regenerate_tokens_admin_path, :class => "btn btn-default"