swarmize-dot-com/config/routes.rb
Swarmize::Application.routes.draw do
  root to: "home#show"

  resources :swarms do
    resources :permissions
    resources :api_keys
    resources :graphs do
      member do
        get 'delete'
      end
    end
    resource :csv, :controller => 'csv' do
      #collection do
        #get 'public'
      #end
    end
    member do
      get 'fields'
      get 'preview'
      get 'embed'
      get 'delete'
      get 'latest'
      get 'entrycount'
      get 'code'
      post 'update_fields'
      post 'open'
      post 'close'
      post 'clone'
    end

    collection do
      get 'mine'
      get 'draft'
      get 'live'
      get 'closed'
    end
  end

  resources :users do
    member do
      get 'delete'
      get 'draft'
      get 'live'
      get 'closed'
    end
  end

  resource :search, :controller => "search" do
    member do
      get 'results'
    end
  end

  resources :case_studies
  resources :docs, :controller => 'documentation'

  resource :home, :controller => "home"

  resource :admin, :controller => "admin" do
    collection do
      post 'dummy_up'
      post 'delete_dummy'
      post 'create_dummy_users'
      post 'create_dummy_swarms'
      post 'regenerate_tokens'
    end
  end

  resource :oembed, :controller => "oembed"

  resource :session do
    collection do
      get 'logout'
    end
  end

  if Rails.env.development?
    resources :swarm_imports, :controller => 'swarm_import'
  end

  get '/utils/name_to_code', to: 'utils#name_to_code'

  get '/auth/google_oauth2', :as => 'login'
  get '/auth/google_oauth2/callback', to: 'sessions#callback'

  get 'swarms/:swarm_id/graphs/count/:count_field', to: 'graphs#aggregate_count'
  get 'swarms/:swarm_id/graphs/count/:count_field/:unique_field', to: 'graphs#cardinal_count'
  get 'swarms/:swarm_id/graphs/count_over_time/:count_field/:interval', to: 'graphs#count_over_time'
end

swarmize-dot-com/app/models/swarm.rb
class TimeParadoxError < StandardError; end

class Swarm < ActiveRecord::Base
  include PgSearch

  acts_as_paranoid

  belongs_to :parent_swarm, class_name: 'Swarm', foreign_key: 'cloned_from'

  has_many :swarm_fields, -> { order('field_index ASC') }, dependent: :destroy
  has_many :graphs
  has_many :clones, class_name: 'Swarm', foreign_key: 'cloned_from'

  has_many :access_permissions
  has_many :unassigned_access_permissions, -> { where('user_id IS NULL') }, class_name: 'AccessPermission'
  has_many :users, through: :access_permissions
  has_many :owners, -> { where('access_permissions.is_owner' => true) }, through: :access_permissions, source: :user

  before_create :setup_token

  before_update :confirm_open_time
  before_update :confirm_close_time

  after_save :dynamo_sync
  after_destroy :dynamo_delete

  scope :latest, lambda {|n|
    limit(n)
  }

  scope :publicly_visible, lambda {
    where("(closes_at < ?) OR (opens_at <= ? AND (closes_at IS NULL or closes_at > ?))", Time.zone.now, Time.zone.now, Time.zone.now).order("opens_at DESC")
  }

  scope :draft, lambda {
    where("opens_at IS NULL OR opens_at > ?", Time.zone.now).order("created_at DESC")
  }

  scope :closed, lambda {
    where("closes_at < ?", Time.zone.now).order("closes_at DESC")
  }

  scope :live, lambda {
    where("opens_at <= ?", Time.zone.now).where("closes_at IS NULL or closes_at > ?", Time.zone.now).order('opens_at DESC')
  }

  pg_search_scope :search_by_name_and_description, against: {
    name: 'A', 
    description: 'B'
  }

  def creator
    owners.order(:created_at).first
  end
  
  def to_param
    token
  end

  def spike!
    self.closes_at = Time.zone.now
    self.destroy
  end

  def as_json(options={})
    {name: self.name,
     description: self.description,
     fields: self.swarm_fields,
     opens_at: self.opens_at,
     closes_at: self.closes_at,
     token: self.token,
     display_title: self.display_title,
     display_description: self.display_description
    }
  end

  def collector_url
    "http://collector.swarmize.com/swarms/#{token}"
  end

  def search
    if draft?
      SwarmizeSearch.new("#{token}_draft")
    else
      SwarmizeSearch.new(token)
    end
  end

  def clone_by(user)
    new_swarm = self.dup
    new_swarm.token = nil
    new_swarm.opens_at = nil
    new_swarm.closes_at = nil
    new_swarm.parent_swarm = self
    #new_swarm.creator = user
    new_swarm.name = self.name + " (cloned)"

    new_swarm.save

    AccessPermission.create(swarm: new_swarm,
                            user: user,
                            email: user.email,
                            is_owner: true)

    self.swarm_fields.each do |f|
      new_f = f.dup
      new_f.swarm = new_swarm
      new_f.save
    end

    new_swarm
  end

  def has_opened?
    opens_at && (opens_at <= Time.zone.now)
  end

  def scheduled_to_open?
    opens_at && (opens_at > Time.zone.now)
  end

  def draft?
    opens_at.nil? || (opens_at > Time.zone.now)
  end

  def live?
    if has_opened?
      if closes_at
        closes_at > Time.zone.now
      else
        true
      end
    elsif opens_at
      opens_at <= Time.zone.now
    end
  end

  def closed?
    closes_at && (closes_at <= Time.zone.now)
  end

  def scheduled_to_close?
    closes_at && (closes_at > Time.zone.now)
  end

  def can_be_edited_by?(u)
    AccessPermission.can_edit? self, u
  end

  def regenerate_token!
    # this is really dangerous
    setup_token
    save
  end

  def field_codes
    output = %w{timestamp}
    swarm_fields.each do |f|
      output << f.field_code
      output << f.derived_field_codes if f.derived_field_codes.any?
    end
    output.flatten
  end

  def public_field_codes
    output = %w{timestamp}
    swarm_fields.each do |f|
      unless f.redacted?
        output << f.field_code
        output << f.derived_field_codes if f.derived_field_codes.any?
      end
    end
    output.flatten
  end

  def api_keys
    keys = []
    APIKey.all.where(swarm_token: self.token).select do |item_data|
        keys << item_data.attributes #=> { 'id' => 'abc', 'category' => 'foo', ... }
    end

    keys.each do |t|
      t['created_by'] = User.find_by(email: t['created_by'])
    end

    keys
  end

  def estimate_form_height
    height = 210

    if swarm_fields.any?
      fields_height = swarm_fields.map do |field|
        case field.field_type
        when 'pick_one', 'pick_several'
          field_height = 30

          if field.possible_values.any?
            field_height = field_height + (30 * field.possible_values.size)
          end

          field_height
        when 'bigtext'
          220
        else
          80
        end
      end.sum 

      height = height + fields_height
    end

    height
  end

  private

  def confirm_open_time
    if self.opens_at && self.opens_at_changed?
      if self.opens_at < Time.zone.now
        self.opens_at = Time.zone.now
      end

      if self.closes_at && (self.opens_at > self.closes_at)
        raise TimeParadoxError, "Swarm cannot close before it has opened!"
      end
    end
  end

  def confirm_close_time
    if self.closes_at && self.closes_at_changed?
      if self.closes_at < Time.zone.now
        self.closes_at = Time.zone.now
      end

      if self.opens_at && (self.closes_at < self.opens_at)
        raise TimeParadoxError, "Swarm cannot close before it has opened!"
      end
    end
  end

  def setup_token
    unless self.token
      t = generate_token
      until !Swarm.find_by_token(t)
        t = generate_token
      end

      self.token = t
    end
  end

  def generate_token(len=8)
    (0...len).map { (65 + rand(26)).chr.downcase }.join
  end

  def dynamo_sync
    DynamoSync.sync(self)
  end

  def dynamo_delete
    DynamoSync.delete(self)
  end

end

swarmize-dot-com/app/controllers/swarms_controller.rb
class SwarmsController < ApplicationController
  before_filter :scope_to_swarm, :except => %w{index draft live closed new create mine embed}
  before_filter :scope_to_swarm_for_embed, :only => %w{embed}
  before_filter :check_for_user, :except => %w{embed}
  before_filter :count_swarms, :only => %w{index draft live closed}
  before_filter :check_user_can_alter_swarm, :only => %w{edit update fields update_fields preview open close code}
  before_filter :check_user_can_destroy_swarm, :only => %w{delete destroy}

  respond_to :html, :json

  def index
    if @current_user
      @swarms = Swarm.order("created_at DESC").paginate(:page => params[:page])
    else
      @swarms = Swarm.order("created_at DESC").publicly_visible.paginate(:page => params[:page])
    end
  end

  def draft
    @swarms = Swarm.order("created_at DESC").draft.paginate(:page => params[:page])
  end

  def live
    @swarms = Swarm.order("created_at DESC").live.paginate(:page => params[:page])
  end
  
  def closed
    @swarms = Swarm.order("created_at DESC").closed.paginate(:page => params[:page])
  end

  def mine
    redirect_to user_path(@current_user)
  end

  def show
    @current_page = 1

    if @swarm.closed? || @current_user
      begin
        @rows, @total_pages = @swarm.search.all(@current_page, 10)
        @total_count = @swarm.search.count_all
      rescue Faraday::TimeoutError, Faraday::ConnectionFailed
        @rows, @total_pages = [], 0
        @elasticsearch_error = "There was an error connecting to Elasticsearch, and results cannot be shown."
      rescue Elasticsearch::Transport::Transport::Errors::NotFound
        @rows, @total_pages = [], 0
        @total_count = 0
      end
    end
    respond_with @swarm
  end

  def latest
    @rows, pages = @swarm.search.all(1,10)
    respond_with @rows
  end

  def entrycount
    respond_with @swarm.search.count_all
  end

  def delete
  end

  def destroy
    @swarm.spike!
    flash[:success] = "'#{@swarm.name}' was deleted."
    redirect_to root_path
  end

  def new
    @swarm = Swarm.new
  end

  def fields
  end

  def update_fields
    # because of the dance we've done
    # around rails' standard form elements
    # to make it possible to have many pairs of
    # display_as_select boxes
    # we now need to make the has look like rails expects.
    manipulated_fields = params[:fields].map do |field|
      if field.keys.detect {|f| f =~ /display_as_select/}
        das_key = field.keys.detect {|f| f =~ /display_as_select/}
        field["display_as_select"] = field[das_key]
        field.delete(das_key)
        field
      else
        field
      end
    end

    if @swarm.has_opened?
      manipulated_fields.each do |f|
        if f[:id]
          field = @swarm.swarm_fields.find(f[:id])
          field.update(f)
        end
      end
    else
      @swarm.swarm_fields.destroy_all

      manipulated_fields.each do |f|
        f['id'] = nil # unset any previously set id
        @swarm.swarm_fields.create(f)
      end
    end

    # has to be called manually, because swarm_fields now a model.
    DynamoSync.sync(@swarm)
    
    if params[:update_and_next]
      redirect_to preview_swarm_path(@swarm)
    else
      redirect_to edit_swarm_path(@swarm)
    end
  end

  def preview
  end

  def embed
    response.headers.delete('X-Frame-Options')
    expires_in 1.minute, :public => true
    
    render layout: 'embed'
  end

  def create
    swarm = Swarm.new(swarm_params)
    swarm.save

    AccessPermission.create(:swarm => swarm,
                            :user => @current_user,
                            :email => @current_user.email,
                            :is_owner => true)

    redirect_to fields_swarm_path(swarm)
  end

  def edit
  end

  def update
    @swarm.update(swarm_params)
    redirect_to fields_swarm_path(@swarm)
  end

  def open
    open_time = Time.zone.local(params['open_year'],
                                params['open_month'],
                                params['open_day'],
                                params['open_hour'],
                                params['open_minute'])
    @swarm.update(:opens_at => open_time)
    redirect_to @swarm
  end

  def close
    close_time = Time.zone.local(params['close_year'],
                                 params['close_month'],
                                 params['close_day'],
                                 params['close_hour'],
                                 params['close_minute'])

    begin
      @swarm.update(:closes_at => close_time)
    rescue TimeParadoxError
      flash[:error] = "Swarm cannot close before it has opened!"
    end
    redirect_to @swarm
  end

  def clone
    new_swarm = @swarm.clone_by(@current_user)
    flash[:success] = "A new swarm has been created from the old, and you've been given full permissions on your new version."
    redirect_to new_swarm
  end

  private

  def scope_to_swarm
    @swarm = Swarm.find_by(token: params[:id])
    if @swarm && @swarm.draft?
      check_for_user
    end
  end

  def scope_to_swarm_for_embed
    @swarm = Swarm.find_by(token: params[:id])
  end

  def check_user_can_alter_swarm
    unless AccessPermission.can_alter?(@swarm, @current_user)
      flash[:error] = "You don't have permission to do that."
      redirect_to root_path
    end
  end

  def check_user_can_destroy_swarm
    unless AccessPermission.can_destroy?(@swarm, @current_user)
      flash[:error] = "You don't have permission to do that."
      redirect_to root_path
    end
  end

  def swarm_params
    params.require(:swarm).permit(:name, :description, :display_title, :display_description)
  end

  def count_swarms
    if @current_user
      @open_swarms_count = Swarm.draft.count
      @all_swarms_count = Swarm.count
    else
      @all_swarms_count = Swarm.publicly_visible.count
    end

    @live_swarms_count= Swarm.live.count
    @closed_swarms_count = Swarm.closed.count
  end
end

swarmize-dot-com/app/views/swarms/_close_swarm_modal.html.haml
#close-or-schedule.modal.fade{:tabindex => -1, :role => 'dialog'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => 'modal'}
          %span{"aria-hidden" => true} &times;
          %span.sr-only Close
        %h4.modal-title Close Swarm
      .modal-body
        = form_tag close_swarm_path(@swarm), :id => "close-date-form" do 
          %p When does your swarm close?
          %p
            At
            - if @swarm.closes_at
              %select{:name => "close_hour"}
                - (00..23).each do |n|
                  %option{:value => n, :selected => (true if n == @swarm.closes_at.hour)}= "%.2d" % n
              \:
              %select{:name => "close_minute"}
                - (00..59).each do |n|
                  %option{:value => n, :selected => (true if n == @swarm.closes_at.min)}= "%.2d" % n
              on
              %select{:name => "close_month"}
                - (1..12).each do |n|
                  %option{:value => n, :selected => (true if n == @swarm.closes_at.month)}= Date::MONTHNAMES[n]

              %select{:name => "close_day"}
                - (1..31).each do |n|
                  %option{:value => n, :selected => (true if n == @swarm.closes_at.day)}= "%.2d" % n
              %select{:name => "close_year"}
                - [2014,2015,2016,2017].each do |n|
                  %option{:value => n, :selected => (true if n == @swarm.closes_at.year)}= n
            - else
              %select{:name => "close_hour"}
                - (00..23).each do |n|
                  %option{:value => n, :selected => (true if n == Time.zone.now.hour)}= "%.2d" % n
              \:
              %select{:name => "close_minute"}
                - (00..59).each do |n|
                  %option{:value => n, :selected => (true if n == Time.zone.now.min)}= "%.2d" % n
              on
              %select{:name => "close_month"}
                - (1..12).each do |n|
                  %option{:value => n, :selected => (true if n == Time.zone.now.month)}= Date::MONTHNAMES[n]

              %select{:name => "close_day"}
                - (1..31).each do |n|
                  %option{:value => n, :selected => (true if n == Time.zone.now.day)}= "%.2d" % n
              %select{:name => "close_year"}
                - [2014,2015,2016,2017].each do |n|
                  %option{:value => n, :selected => (true if n == Time.zone.now.day)}= n
            = link_to "Set to now", "#", :id => "set-close-date-to-now", :class => "btn btn-primary btn-sm"

        %p
          %i All times are London time (ie GMT/BST dependent on time of year).
        %p 
          %b Once your swarm has opened it cannot be closed and re-opened at a later date.
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => 'modal'} Cancel
        %button#close-submit.btn.btn-primary Save changes

swarmize-dot-com/app/views/swarms/_embed_closed.html.haml
.embeddable-swarm
  - if @swarm.display_title
    %h2= @swarm.name
  - if @swarm.display_description
    .explanation= simple_format @swarm.description
  .closed
    This swarm is now closed, and is no longer accepting responses.

  .small
    Powered by
    %b Swarmize.

swarmize-dot-com/app/views/swarms/_field_code_update_js.html.haml
:javascript
  $(document).ready(function() {
    $(".code-text-block a.alter").click(function(e) {
      $(this).parents('.form-group').find('.field-code-block').show();
      $(this).parents('.code-text-block').hide();
      e.preventDefault();
    });

    $("input.field-name").unbind('change').on('change', function(e) {
      if(!('hasCustomFieldCode' in $(this).parents('.form-element').data())) {
        var fieldCode = $(this).val();
        var codeField = $(this).parents('.form-element').find('.field-code');
        var codeText = $(this).parents('.form-element').find('.code-text');
        $.get("/utils/name_to_code", {name: fieldCode}, function(data) {
          $(codeField).val(data);
          $(codeText).text(data);
        });
      }
    });

    $("input.field-code").unbind('focus').on('focus', function(e) {
      console.log('focus');
      $(this).data('code-pre-alter', $(this).val());
      console.log($(this).data());
    });

    $("input.field-code").unbind('change').on('change', function(e) {
      if('codePreAlter' in $(this).data()) {
        if($(this).val() != $(this).data('codePreAlter')) {
          console.log("changed by hand, noting this is a custom field code");
          $(this).parents('.form-element').data('hasCustomFieldCode', true);
        }
      }
    });
  });

swarmize-dot-com/app/views/swarms/_swarm_dropdown_menu.html.haml
.dropdown.actions-dropdown
  %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown"} 
    Actions
    %span.caret
  %ul.dropdown-menu.dropdown-menu-right
    %li
      = link_to "<span class='glyphicon glyphicon-retweet'></span> Clone".html_safe, clone_swarm_path(@swarm), :method => :post
      %li.divider
    - if AccessPermission.can_alter?(@swarm, @current_user) && !@swarm.closed?
      %li
        %a{:href => edit_swarm_path(@swarm)}
          = glyphicon('pencil')
          Edit 

    - if AccessPermission.can_alter?(@swarm, @current_user) 
      %li
        %a{:href => code_swarm_path(@swarm)}
          = glyphicon('th-list')
          Get Code
      %li
        %a{:href => swarm_api_keys_path(@swarm)}
          = glyphicon('tag')
          API Keys
    %li
      %a{:href => swarm_permissions_path(@swarm)}
        = glyphicon('user')
        Permissions
    - if AccessPermission.can_destroy?(@swarm, @current_user)
      %li.divider
      %li
        %a{:href => delete_swarm_path(@swarm)}
          = glyphicon('remove')
          Delete

swarmize-dot-com/app/views/swarms/_swarm_graphs.html.haml
%h2 Graphs

- @swarm.graphs.each_with_index do |graph, i|
  = render :partial => "graphs/#{graph.graph_type}", :locals => {:graph => graph, :count => i}

#graphs

.clearfix

swarmize-dot-com/app/views/swarms/code.html.haml
- content_for :pagetitle do
  Code for #{@swarm.name} : Swarms : 

.page-header.swarmize-header
  %h1 
    Code for '#{@swarm.name}'
  %p
    %a{:href => swarm_path(@swarm)}
      = glyphicon('circle-arrow-left')
      Back to swarm
%dl
  %dt Embed code
  %dd
    %textarea{style: 'width: 400px; height: 150px;'}
      #{"<script type='text/javascript' src='//cdn.swarmize.com/js/swarmize-embed.js'></script><div id='swarmize-embedded-form' data-swarmize-token='#{@swarm.token}'><a href='#{embed_swarm_url(@swarm)}'>Fill out your answers on swarmize.com</a></div>"}

  %dt Token
  %dd
    %code= @swarm.token

  %dt Collector URL
  %dd
    %code= @swarm.collector_url

%table.table
  %thead
    %tr
      %th Field name
      %th Field code
      %th Field type
      %th Possible values
  %tbody
    - @swarm.swarm_fields.each do |f|
      %tr
        %td= f.field_name
        %td
          %code= f.field_code
        %td
          %code= f.field_type
        %td
          - case f.field_type
          - when 'yesno'
            %code yes
            %br
            %code no
          - when 'rating'
            %code #{f.minimum}...#{f.maximum}
          - when 'pick_one', 'pick_several'
            - if f.possible_values
              - f.possible_values.each do |v|
                %code= v.parameterize.underscore
                %br

%p= link_to "API Documentation", doc_path('api')

swarmize-dot-com/app/views/swarms/draft.html.haml
- content_for :pagetitle do
  Yet To Open : Swarms : 

%h1 Explore Swarms

%ul.nav.nav-tabs
  %li
    %a{:href => swarms_path}
      All Swarms
      %span.badge= @all_swarms_count
  %li.active
    %a{:href => draft_swarms_path}
      Draft
      %span.badge= @open_swarms_count
  %li
    %a{:href => live_swarms_path}
      In Progress
      %span.badge= @live_swarms_count
  %li
    %a{:href => closed_swarms_path}
      Closed
      %span.badge= @closed_swarms_count

= render :partial => "swarms/swarm_table", :locals => {:swarms => @swarms}

= will_paginate @swarms

- if @current_user
  %p= link_to "New swarm", new_swarm_path

swarmize-dot-com/app/views/swarms/live.html.haml
- content_for :pagetitle do
  Live Swarms : Swarms : 

%h1 Explore Swarms

%ul.nav.nav-tabs
  %li
    %a{:href => swarms_path}
      All Swarms
      %span.badge= @all_swarms_count
  - if @current_user
    %li
      %a{:href => draft_swarms_path}
        Draft
        %span.badge= @open_swarms_count
  %li.active
    %a{:href => live_swarms_path}
      In Progress
      %span.badge= @live_swarms_count
  %li
    %a{:href => closed_swarms_path}
      Closed
      %span.badge= @closed_swarms_count

= render :partial => "swarms/swarm_table", :locals => {:swarms => @swarms}

= will_paginate @swarms

- if @current_user
  %p= link_to "New swarm", new_swarm_path

swarmize-dot-com/app/views/swarms/new.html.haml
- content_for :pagetitle do
  Create Swarm : Swarms :

.page-header.swarmize-header
  %h1 Create Swarm

%ul.nav.nav-tabs.swarmbuilder-nav.nav-justified
  %li.disabled.active
    %a{:href => new_swarm_path}
      = glyphicon('pencil')
      Swarm Details
  %li.disabled
    %a{:href => '#'}
      = glyphicon('list')
      Swarm Fields
  %li.disabled
    %a{:href => '#'}
      = glyphicon('list-alt')
      Preview Swarm

= form_for @swarm, :html => {:class => "form-horizontal"} do |f|
  .form-group
    %label.col-sm-3.control-label Swarm name
    .col-sm-6
      = f.text_field :name, :class => 'form-control'
      %span.help-block This is the public name your swarm will be known by. This will be used across Swarmize.com, even if you don't display it with the input for your Swarm.

  .form-group
    %label.col-sm-3.control-label Swarm description
    .col-sm-6
      = f.text_area :description, :class => 'form-control'
      %span.help-block A short description of your Swarm. This will be used across Swarmize.com, even if you don't display it with the input for your Swarm.

  .form-group
    %label.col-sm-3.control-label Display title on embedded form?
    .col-sm-9
      = f.check_box :display_title, :class => 'form-control check'

  .form-group
    %label.col-sm-3.control-label Display description on embedded form?
    .col-sm-9
      = f.check_box :display_description, :class => 'form-control check'

  .form-group
    .col-sm-offset-3
      %p= f.submit "Add fields &rarr;".html_safe, :class => "btn btn-default"
      %p= link_to "Back to all swarms", swarms_path

swarmize-dot-com/app/views/swarms/preview.html.haml
- content_for :pagetitle do
  Preview '#{@swarm.name}' : Swarms : 

.page-header.swarmize-header
  %h1 Preview '#{@swarm.name}'
  %p= link_to "Back to swarm", @swarm

%ul.nav.nav-tabs.swarmbuilder-nav.nav-justified
  %li
    %a{:href => edit_swarm_path(@swarm)}
      = glyphicon('pencil')
      Swarm Details
  %li
    %a{:href => fields_swarm_path(@swarm)}
      = glyphicon('list')
      Swarm Fields
  %li.active
    %a{:href => preview_swarm_path(@swarm)}
      = glyphicon('list-alt')
      Preview Swarm

%script{type: 'text/javascript', src: '/js/swarmize-embed.js'}
#swarmize-embedded-form{"data-swarmize-token" => @swarm.token}
  = link_to "Fill out your answers on swarmize.com", embed_swarm_path(@swarm)

%p
  = link_to "&larr; Alter fields".html_safe, fields_swarm_path(@swarm), :class => "btn btn-default"
  = link_to "Done!", @swarm, :class => "btn btn-default"

%p= link_to "Back to swarm", @swarm

swarmize-dot-com/app/views/swarms/show.html.haml
- content_for :pagetitle do
  '#{@swarm.name}' : Swarms : 

- content_for :oembed_discovery do
  %link{rel: 'alternate', type: 'application/json+oembed', title: "#{@swarm.name} embeddable form", href: oembed_url(url: swarm_url(@swarm))}

= render :partial => "swarms/swarm_page_js"

= render :partial => "swarms/swarm_header"

- if AccessPermission.can_alter?(@swarm, @current_user)
  = render :partial => "swarms/swarm_description_open_close_logged_in"
- else
  = render :partial => "swarms/swarm_description_open_close"

%hr

- if (@swarm.closed? || @current_user) && !@elasticsearch_error
  -if @swarm.graphs.any?
    :javascript
      window.graphDataCache = {};
    = render "swarms/swarm_graphs"
  -elsif AccessPermission.can_alter?(@swarm, @current_user)
    %h2 Graphs

  - if AccessPermission.can_alter?(@swarm, @current_user)
    %p= link_to "Manage swarm graphs", swarm_graphs_path(@swarm)

- if @swarm.closed? || @current_user
  %h2 
    %hr.divider
    Results
    - if @current_user
      %a.btn.btn-default{:href => swarm_csv_path(@swarm), :style => "float:right"}
        = glyphicon('file')
        CSV
    - else
      - if Rails.env.production?
        %a.btn.btn-default{:href => serve_from_cloudfront(public_swarm_csv_path(@swarm)), :style => "float:right"}
          = glyphicon('file')
          CSV
      - else
        %a.btn.btn-default{:href => public_swarm_csv_path(@swarm), :style => "float:right"}
          = glyphicon('file')
          CSV

  .clearfix

  - if @elasticsearch_error
    %p= @elasticsearch_error
  - else
    = render :partial => "swarms/swarm_results"
- else
  %hr.divider
  %h2 Results
  %p Results will appear here when the swarm is complete.

= render "swarms/open_swarm_modal"
= render "swarms/close_swarm_modal"

swarmize-dot-com/app/views/swarms/yet_to_open.html.haml
- content_for :pagetitle do
  Yet To Open : Swarms : 

%h1 All Swarms

%ul.nav.nav-tabs
  %li
    %a{:href => swarms_path}
      All Swarms
      %span.badge= @all_swarms_count
  %li.active
    %a{:href => yet_to_open_swarms_path}
      Yet To Open
      %span.badge= @open_swarms_count
  %li
    %a{:href => live_swarms_path}
      In Progress
      %span.badge= @live_swarms_count
  %li
    %a{:href => closed_swarms_path}
      Closed
      %span.badge= @closed_swarms_count

= render :partial => "swarms/swarm_table", :locals => {:swarms => @swarms}

= will_paginate @swarms

- if @current_user
  %p= link_to "New swarm", new_swarm_path